import { Box, Button, Center, Container, HStack, Text } from "@chakra-ui/react";
import Emoji from "a11y-react-emoji";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import doodle from "../public/doodle.webp";
import logo from "../public/logo.webp";

const Home: NextPage = () => {
  const [levelOfInformation, setLevelOfInformation] = useState(0);

  const showMoreInformation = () => {
    setLevelOfInformation((prev) => prev + 1);
  };

  const resetLevelOfInformation = () => {
    setLevelOfInformation(0);
  };

  return (
    <>
      <Head>
        <title>Ronna Firmo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="100vh" pos="relative">
        <Container maxW="container.xl" px={16}>
          <Center py={24}>
            <Image src={logo} alt="Logo" width={60} height={60} />
          </Center>
          <Box>
            <Text fontSize="2xl">
              Hi <Emoji symbol="👋" label="wave" />
            </Text>
            <Box my={4} />
            <Text fontSize="4xl">
              I&apos;m <strong>Ronna</strong>, a software engineer based in
              Iloilo City PH.
            </Text>
            <Box my={8} />
            <Text w={{ lg: "100%", xl: "70%" }} lineHeight={2}>
              I build web and mobile apps with React, React Native, Flutter and
              Node.js. I love seeing my work come to life and being used by
              other people! I strive to keep myself in the loop for new tools
              that make our lives easier, and I care deeply about writing code
              that humans can understand.
              {levelOfInformation >= 1 && (
                <>
                  <br />I have a pupper named Maui, she&apos;s a poodle. She
                  bites me often and that&apos;s how I know she loves me!
                </>
              )}
              {levelOfInformation >= 2 && (
                <>
                  <br />I kinda hate coding sometimes. If I&apos;m not a
                  software engineer, I would love to help rescue animals like
                  find stray dogs new homes, or free a sea turtle from a net—
                  those poor things!
                </>
              )}
            </Text>
            <Box my={6} />
            {levelOfInformation === 0 && (
              <Button size="sm" onClick={showMoreInformation}>
                Show more
              </Button>
            )}
            {levelOfInformation === 1 && (
              <Button size="sm" onClick={showMoreInformation}>
                Show too much information...
              </Button>
            )}
            {levelOfInformation === 2 && (
              <HStack alignItems="center">
                <Button size="sm" onClick={resetLevelOfInformation}>
                  Show less
                </Button>
                <Emoji symbol="😬" label="wave" />
              </HStack>
            )}
          </Box>
        </Container>
        <Box
          pos="absolute"
          bottom="10%"
          right="10%"
          width="30%"
          minW="512px"
          maxW="672px"
          opacity={0.15}
        >
          <Image src={doodle} alt="Logo" />
        </Box>
      </Box>
    </>
  );
};

export default Home;
